//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pharmacy
{
    using System;
    using System.Collections.Generic;
    
    public partial class billSale
    {
        public string saleName { get; set; }
        public string totalAmount { get; set; }
        public System.DateTime dateCreated { get; set; }
        public int Id { get; set; }
        public string billINumber { get; set; }
    
        public virtual bill bill { get; set; }
    }
}
