//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pharmacy
{
    using System;
    using System.Collections.Generic;
    
    public partial class sale
    {
        public int saleId { get; set; }
        public Nullable<int> stockId { get; set; }
        public string saleName { get; set; }
        public string repName { get; set; }
        public string salePrice { get; set; }
        public Nullable<int> saleQuantity { get; set; }
        public System.DateTime dateCreated { get; set; }
        public Nullable<int> totalQuantity { get; set; }
        public string totalAmount { get; set; }
        public string saleTotal { get; set; }
        public string billNumber { get; set; }
    
        public virtual bill bill { get; set; }
    }
}
